# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master
resources:
  containers:
  - container: python
    image: python:latest
    options: '-u 0'

jobs:
  - job: 'Phase1'
    displayName: 'Install Requirements and run Unit tests'
    pool:
      vmImage: 'ubuntu-latest'
    container: python
    steps:
      - script: |
          python3 -m venv env
          source ./env/bin/activate 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName:  'Install dependencies'
      - script: |
          source ./env/bin/activate
          python -m pytest  --junitxml=Tests_Result.xml --cov=. --cov-report xml:coverage-reports/Tests_coverage.xml --cov-report html:coverage-reports --cov-report annotate:coverage-reports --cov-report term-missing
        displayName:  'Run unit tests'
      - task: PublishTestResults@2
        displayName: 'publish test reports'
        inputs:
          testResultsFiles: '**/Tests*.xml'
          testRunTitle: 'Publish test run result and coverage'


  - job : 'Phase2'
    displayName: 'Build and Push Image'
    dependsOn: 'InstallAndTest'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        displayName: 'build and push image'
        inputs:
          command: buildAndPush
          repository: bootcampp.azurecr.io
          tags: |
           - bootcamp_ms1:latest
      - script: |
          docker image ls
        displayName: 'list docker images'

